#POST http://localhost:8180/realms/kdg/protocol/openid-connect/token
#Content-Type: application/x-www-form-urlencoded
#
#client_id = landside_client &
#client_secret = ToYvMNQKxFA1AXSdWZ4xIWRNVgkJ9HNV &
#username = developer &
#password = password &
#grant_type = password &
#scope = openid
#
#//saving the access token
#> {%
#    client.global.set("access_token", response.body.access_token);
#    console.log("Access Token:", client.global.get("access_token"));
#%}
#

### GET storage fee
GET http://localhost:8093/bcc/commissions/6ac73813-d69a-4ccf-86ca-685f6503314f/2025-08-23
#Authorization: Bearer {{access_token}}
#Accept: application/json
