server:
  port: ${PORT:8091}
  servlet:
    context-path: /bca


spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:33066/kdg"
    username: kdg_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}