server:
  port: ${PORT:8092}
  servlet:
    context-path: /bcb

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:mysql://localhost:33066/kdg"
    username: kdg_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    initialization-mode: always
  #    schema: classpath:schema.sql
  #    data: classpath:data.sql
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/kdg/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/kdg
